### ISSUE TITLE
Use kubernetes annotations to store instance information instead of redis

### ISSUE THREAD

**Issue by J12934** [iteratec/multi-juicer#25]
MultiJuicer currently depends on redis as a datasource.
MultiJuicer stores 3 pieces of data related to every instance in redis:

1. **Passcode:** Bcrypt hash of the instances passcode
2. **LastRequest:** Timestamp of the last request proxied to the instance. Update at most every 10 seconds to reduce load.
3. **ContinueCode:** JuiceShop ContinueCode to backup the current Instance Progress.

All of the data could be stored directly on the instance, as annotations on the Instances kubernetes deployment or directly on the pod. This would enable to remove redis entirely. This would make the setup easier as no persistent volumes are required and removed a potential point of failure.

**Comment by J12934** [comment]
Made a ton of progress on this today.

Was able to replace all redis dependencies and move them to the annotations on the JuiceShop deployments. This seems to work out great so far!

## Structure of the new annotations

The annotations are structured like the following:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    multi-juicer.iteratec.dev/challengesSolved: "42"
    multi-juicer.iteratec.dev/continueCode: "LRo3lzE7XYnWkwaZNdE7i3Hku6TqCQiW8i5NF96H2b0yPxve5Mq4pK18VJmg"
    multi-juicer.iteratec.dev/lastRequest: "1581010161979"
    multi-juicer.iteratec.dev/lastRequestReadable: "Thu Feb 06 2020 17:29:21 GMT+0000 (Coordinated Universal Time)"
    multi-juicer.iteratec.dev/passcode: $2a$12$bGiBDC0wYE23TSRSeNIUaOk2mMU3QgfV9hgem7NCj4W2J/UjyGnpi
  labels:
    app: juice-shop
    deployment-context: multi-juicer
    team: team42
spec:
# deployment spec ...
```

The fields `challengesSolved` and `lastRequestReadable` are kind of duplicated technically but make debugging a lot easier. 

And enables you to see all important information within `kubectl` e.g. via custom-column template like: https://github.com/iteratec/multi-juicer/blob/3de9964de5e586b3457e77d2c4846735932bbf00/juiceShop.txt

This looks like the following when used with `kubectl`:

<img width="874" alt="Screenshot 2020-02-06 at 20 09 03" src="https://user-images.githubusercontent.com/13718901/73970504-96235a80-491d-11ea-8da9-72f492f34c58.png">

Neat, right 😉

## Changes to the ProgressWatchdog

I had to make one big(ish) architecture change for this. Previously the `progress-watchdog`, the component reading JuiceShop continueCodes and saving them was running as a sidecar in every JuiceShop container. This made it easier as every ProgressWatchdog was only responsible for its own container. The ProgressWatchdog now runs in a single deployment, which managed all JuiceShop instances.

This was changed for two reasons:

1. The ProgressWatchdog now needs write access to the kubernetes api (the exact permission can be viewed on the [progress-watchdog role](https://github.com/iteratec/multi-juicer/blob/no-redis/helm/multi-juicer/templates/progresswatchdog-role.yaml)). To make this possible we have to mount the access token for the progress-watchdog into the pod. The access tokens are availible to all container in the pod, which would for the sidecar mean that JuiceShop users could access the kubernetes api and change deployments as they wish. This seemed just a bit too dangerous to me 😉 .
2. Having a ProgressWatchdog running in every container running consumed about 10Mib of additional RAM for every JuiceShop instance just for the golang runtime overhead. Having this handled in one place is more efficient. The in / exporting is pretty quick and runs in 10 seperate goroutines (at the moment). That should be able to easily manage thousands JuiceShops at the same time. When somebody has more JuiceShop, we'd can always increase the number of goroutines. But i don't really expect setups this big.

So this should basically be safer and more efficient for pretty much any setups.

## Timeline

To see if this is all relatively stable, I'll need some more time and tweaks.
I'm currently planning for that to get released during the OWASP Winter Summit (End of February), but no promises 😉
