### ISSUE TITLE
SecurityContext should support runAsUser

### ISSUE THREAD

**Issue by DerGut** [iteratec/multi-juicer#60]
I have an issue with my PodSecurityPolicy specifying `runAsNonRoot` as `true`.

The JuiceBalancer already uses the non-root user `app` but Kubernetes needs a numeric id in order to verify that it is not the root user:
```
Error: container has runAsNonRoot and image has non-numeric user (app), cannot verify user is non-root
```
For this to work, the pod securityContext needs to specify `runAsUser` with the according user id of app.

I would love a change to either:
 1. include the numeric id of the app user in the template:
```yaml
-- helm/multi-juicer/templates/juice-balancer-deployment.yaml

securityContext:
  runAsUser: 100
  runAsGroup: 101
```
 2. or include a template variable for the pod securityContext, so that users can modify it themselves:
```yaml
-- helm/multi-juicer/templates/juice-balancer-deployment.yaml

{{- if .Values.balancer.securityContext }}
securityContext:
  {{ toYaml .Values.balancer.securityContext | indent 8 }}
{{- end }}
```
```yaml
-- helm/multi-juicer/values.yaml

balancer:
  securityContext: {}
```
